[package]
name = "maplestory-calculator"
version = "0.1.0"
authors = ["Jimmy Ye <jiy162@ucsd.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [profile.release]
# debug = true

[dependencies]
lazy_static = "1.4.0"
fixed = "1.5.0"
priority-queue = "1.0.5"
rustc-hash = "1.1.0"
